<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:ivy="antlib:org.apache.ivy.ant" name="qldarch.backend" default="build">

  <property name="ivy.install.version" value="2.4.0"/>
  
  <target name="clean">
    <delete dir="build"/>
  </target>

  <target name="retrieve" description="retrieve dependencies with ivy">
    <mkdir dir="ivy/lib" />
    <get src="https://repo1.maven.org/maven2/org/apache/ivy/ivy/${ivy.install.version}/ivy-${ivy.install.version}.jar"
         dest="ivy/ivy-${ivy.install.version}.jar" usetimestamp="true"/>
    <path id="ivy.lib.path"><fileset dir="ivy/" includes="*.jar"/></path>
    <taskdef resource="org/apache/ivy/ant/antlib.xml"
             uri="antlib:org.apache.ivy.ant" classpathref="ivy.lib.path"/> 

    <ivy:configure file="ivysettings.xml"/>
    <!-- <ivy:cleancache/> -->
    <ivy:retrieve pattern="ivy/lib/[conf]/[artifact]-[revision].[ext]" type="jar, bundle" sync="true"/>
    <mkdir dir="ivy/lib/compile" />
    <get src="https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/6.1.0/jakarta.servlet-api-6.1.0.jar"
     dest="ivy/lib/compile/jakarta.servlet-api-6.1.0.jar" usetimestamp="true"/>     
  </target>

  <target name="compile" depends="retrieve">
    <mkdir dir="build/classes"/>
    <javac srcdir="src" destdir="build/classes" deprecation="on" debug="true"
           includeantruntime="false" source="21" target="21">
      <classpath>
        <fileset dir="ivy/lib/default"/>
        <fileset dir="ivy/lib/compile"/>
        <fileset dir="lib/default" includes="*.jar"/> 
      </classpath>
    </javac>
  </target>

  <target name="build" depends="compile">
    <copy todir="build/classes">
      <fileset dir="src">
        <exclude name="**/*.java"/>
      </fileset>
    </copy>
    <copy file="version.txt" todir="build/classes/net/qldarch"/>
    <loadfile property="version" srcFile="version.txt">
      <filterchain>
        <striplinebreaks/>
      </filterchain>
    </loadfile>
    <war destfile="build/qldarch-${version}.war" webxml="web.xml">
      <classes dir="build/classes"/>
      <lib dir="ivy/lib/default"/>
      <lib dir="lib/default"/>
    </war>
  </target>

</project>
