<ivy-module version="2.0">
  <info organisation="menad" module="qldarch"/>
  <dependencies>
    <dependency org="org.apache.commons" name="commons-lang3" rev="3.12.0"/>
    <dependency org="commons-lang" name="commons-lang" rev="2.6"/>
    <dependency org="commons-io" name="commons-io" rev="2.11.0" />
    <dependency org="com.google.guava" name="guava" rev="31.1-jre" />
    <dependency org="commons-dbutils" name="commons-dbutils" rev="1.7" />
    <dependency org="com.google.code.gson" name="gson" rev="2.10.1" />
    <dependency org="org.danilopianini" name="gson-extras" rev="0.2.1" />
    <dependency org="com.github.spullara.mustache.java" name="compiler" rev="0.9.4" />
    <dependency org="org.reflections" name="reflections" rev="0.10.2" />
    <dependency org="commons-codec" name="commons-codec" rev="1.15"/>
    <dependency org="com.codepoetics" name="protonpack" rev="1.15" />
    <dependency org="net.jcip" name="jcip-annotations" rev="1.0" />

    <!-- Jakarta APIs - required for Tomcat 11 -->
    <dependency org="jakarta.annotation" name="jakarta.annotation-api" rev="2.1.1"/>
    <dependency org="jakarta.ws.rs" name="jakarta.ws.rs-api" rev="3.1.0"/>
    <dependency org="jakarta.xml.bind" name="jakarta.xml.bind-api" rev="4.0.0"/>
    <dependency org="jakarta.validation" name="jakarta.validation-api" rev="3.0.2"/>
    <dependency org="jakarta.activation" name="jakarta.activation-api" rev="2.1.2"/>

    <!-- Mail -->
    <dependency org="org.apache.james" name="apache-mime4j" rev="0.8.4"/>
    <dependency org="jakarta.mail" name="jakarta.mail-api" rev="2.1.2"/>
    <!-- <dependency org="com.sun.mail" name="jakarta.mail" rev="2.0.1"/> -->
    <dependency org="org.eclipse.angus" name="angus-activation" rev="2.0.1"/>
    <dependency org="org.eclipse.angus" name="angus-mail" rev="2.0.1"/>

    <!-- RESTEasy 6.2.x transitive deps - explicitly declared -->
    <dependency org="org.jboss.resteasy" name="resteasy-core" rev="6.2.7.Final"/>
    <dependency org="org.jboss.resteasy" name="resteasy-core-spi" rev="6.2.7.Final"/>
    <dependency org="org.jboss.resteasy" name="resteasy-servlet-initializer" rev="6.2.7.Final"/>
    <dependency org="org.jboss.resteasy" name="resteasy-multipart-provider" rev="6.2.7.Final"/>
    <dependency org="org.jboss.resteasy" name="resteasy-tracing-api" rev="1.0.0.Final"/>
    <dependency org="org.jboss.resteasy" name="resteasy-client" rev="6.2.7.Final" conf="default->default"/>
    <dependency org="org.jboss.resteasy" name="resteasy-jackson2-provider" rev="6.2.7.Final" conf="default->default"/>

    <dependency org="com.fasterxml.jackson.core" name="jackson-annotations" rev="2.15.2" conf="default->default"/>
    <dependency org="com.fasterxml.jackson.jakarta.rs" name="jackson-jakarta-rs-base" rev="2.15.2" conf="default->default"/>
    <dependency org="com.fasterxml.jackson.jakarta.rs" name="jackson-jakarta-rs-json-provider" rev="2.15.2" conf="default->default"/>
    <dependency org="com.fasterxml.jackson.module" name="jackson-module-jakarta-xmlbind-annotations" rev="2.15.2" conf="default->default"/>

    <!-- JSON Patch (pulled by resteasy-client) -->
    <dependency org="com.github.java-json-tools" name="json-patch" rev="1.13" conf="default->default"/>

    <dependency org="com.github.java-json-tools" name="jackson-coreutils" rev="2.0" conf="default->default"/>
    <dependency org="com.github.java-json-tools" name="msg-simple" rev="1.2" conf="default->default"/>

    <!-- RESTEasy missing transitive deps -->
    <dependency org="org.reactivestreams" name="reactive-streams" rev="1.0.4"/>
    <dependency org="com.ibm.async" name="asyncutil" rev="0.1.0"/>
    <dependency org="org.jboss" name="jandex" rev="3.1.2"/>

    <!-- Guice 7.x - Jakarta EE compatible -->
    <dependency org="com.google.inject" name="guice" rev="7.0.0"/>
    <dependency org="com.google.inject.extensions" name="guice-servlet" rev="7.0.0"/>

    <!-- RESTEasy Guice integration - manually declared -->
   <!--  <dependency org="org.jboss.resteasy" name="resteasy-guice" rev="6.2.7.Final"/> -->
    <!-- <dependency org="dev.resteasy.guice" name="resteasy-guice" rev="2.0.0.Final"/> -->

    <!-- Lucene -->
    <dependency org="org.apache.lucene" name="lucene-core" rev="8.11.3"/>
    <dependency org="org.apache.lucene" name="lucene-queryparser" rev="8.11.3"/>
    <dependency org="org.apache.lucene" name="lucene-queries" rev="8.11.3"/>
    <dependency org="org.apache.lucene" name="lucene-sandbox" rev="8.11.3"/>
    <dependency org="org.apache.lucene" name="lucene-analyzers-common" rev="8.11.3"/>

    <dependency org="org.apache.tika" name="tika-core" rev="1.28.5"/>
    <dependency org="org.apache.tika" name="tika-parsers" rev="1.28.5"/>

    <dependency org="org.projectlombok" name="lombok" rev="1.18.30"/>

    <dependency org="org.slf4j" name="slf4j-api" rev="2.0.11"/>
    <dependency org="ch.qos.logback" name="logback-classic" rev="1.4.14"/>

    <dependency org="org.apache.shiro" name="shiro-all" rev="1.13.0"/>

    <dependency org="net.coobird" name="thumbnailator" rev="0.4.8"/>

    <dependency org="com.fasterxml.jackson.core" name="jackson-databind" rev="2.13.4.2"/>
    <dependency org="com.fasterxml.jackson.core" name="jackson-core" rev="2.13.4"/>

    <dependency org="com.twelvemonkeys.imageio" name="imageio-core" rev="3.9.4"/>
    <dependency org="com.twelvemonkeys.imageio" name="imageio-tiff" rev="3.9.4"/>

    <dependency org="org.apache.httpcomponents" name="httpclient" rev="4.5.14">
      <artifact name="httpclient" type="jar"/>
    </dependency>
    <dependency org="com.jayway.jsonpath" name="json-path" rev="2.7.0"/>

    <!-- Hibernate 6.x - Jakarta EE + Java 21 compatible -->
    <!-- <dependency org="org.hibernate.orm" name="hibernate-core" rev="6.4.4.Final"/> -->
    <!-- <dependency org="org.hibernate" name="hibernate-core" rev="5.6.15.Final"/> -->

    <dependency org="org.hibernate.orm" name="hibernate-core" rev="6.4.4.Final"/>
    <dependency org="org.hibernate.orm" name="hibernate-community-dialects" rev="6.4.4.Final"/>
    <dependency org="jakarta.persistence" name="jakarta.persistence-api" rev="3.1.0"/>
    <dependency org="jakarta.transaction" name="jakarta.transaction-api" rev="2.0.1"/>


    <dependency org="com.github.dfabulich" name="sitemapgen4j" rev="1.0.6"/>

    <!-- <dependency org="jakarta.persistence" name="jakarta.persistence-api" rev="3.1.0"/> -->
    <dependency org="jakarta.transaction" name="jakarta.transaction-api" rev="2.0.1"/>
    <dependency org="org.codehaus.jackson" name="jackson-core-asl" rev="1.9.13"/>
    <dependency org="org.codehaus.jackson" name="jackson-mapper-asl" rev="1.9.13"/>

    <dependency org="org.apache.poi" name="poi" rev="5.2.3"/>
    <dependency org="org.apache.poi" name="poi-ooxml" rev="5.2.3"/>

    <exclude org="org.apache.james" module="apache-mime4j-core"/>
    <exclude org="org.apache.james" module="apache-mime4j-dom"/>
    <exclude org="org.jboss.resteasy" module="resteasy-jaxb-provider"/>
    <exclude org="org.slf4j" module="slf4j-simple"/>
    <!-- <exclude org="jakarta.persistence"/> -->
    <exclude org="jakarta.servlet"/>
    <exclude org="jakarta.el"/>
    <exclude org="log4j" module="log4j"/>
    <exclude org="junit" module="junit"/>
    <exclude org="org.apache.logging.log4j" module="log4j-api"/>
  </dependencies>
</ivy-module>