name: CI

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and release latest snapshot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set version
        run: echo "latest" > version.txt

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Verify Java version
        run: java -version && javac -version

      - name: Build with Ant
        run: ant clean build

      - name: Git tag
        run: git tag -f snapshot && git push --tags -f

      - name: Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: snapshot
          name: latest-snapshot
          prerelease: true
          gzip: false
          allow_override: true
          files: build/qldarch-latest.war