name: CI

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    branches: [ master ]

jobs:
  build:
    name: Build with ant
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Ant
        run: ant build

      - uses: actions/upload-artifact@v2
        with:
          name: war
          path: build/*.war